SELECT PRINTER_DRIVER_NAME,
USER_PRINTER_DRIVER_NAME ,
PRINTER_DRIVER_METHOD_CODE ,
SPOOL_FLAG ,
SRW_DRIVER ,
COMMAND_NAME , ARGUMENTS ,
INITIALIZATION , RESET 
 FROM FND_PRINTER_DRIVERS WHERE PRINTER_DRIVER_NAME =( SELECT PRINTER_DRIVER  FROM FND_PRINTER_INFORMATION WHERE
 PRINTER_STYLE=( SELECT  PRINT_STYLE FROM  FND_CONCURRENT_REQUESTS where request_id=4072541    ) AND
  PRINTER_TYPE=(    SELECT PRINTER_TYPE  FROM FND_PRINTER WHERE
 PRINTER_NAME=(   SELECT  PRINTER  FROM  FND_CONCURRENT_REQUESTS where request_id=4072541 )))
